# Generated by Django 4.0.4 on 2022-04-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decrypt', '0002_filelist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
