# Generated by Django 4.0.4 on 2022-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decrypt', '0004_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.AddField(
            model_name='filelist',
            name='decrypted',
            field=models.BooleanField(default=False),
        ),
    ]
